### ISSUE TITLE
Duplicate field names

### ISSUE THREAD

**Issue by RichardScottOZ** [kinverarity1/aseg_gdf2#24]
Here's a question

I was going to turn the Point Located Data from here:- https://ecat.ga.gov.au/geonetwork/srv/eng/catalog.search#/metadata/133023

into a dataframe - however, two field short names are the same in the .dfn file

Is there a code way to fix that? 
e.g. if I randomly edit by hand will it cause problems?

[2019_National_Gravity_Grids_Ground_Gravity_PLD.txt](https://github.com/kinverarity1/aseg_gdf2/files/5923732/2019_National_Gravity_Grids_Ground_Gravity_PLD.txt)

Thanks,

Richard

**Comment by kinverarity1** [comment]
That's a great question! Looking into it. I'm sure we can do it in the code.

**Comment by RichardScottOZ** [comment]
DEFN 6 ST=RECD,RT=;GEOID_G2:F16.3:NULL=99999,NAME=GEOID_GROUND_ELEVATION
DEFN 10 ST=RECD,RT=;GEOID_G1:F16.3:NULL=99999,NAME=GEOID_GRAVITY_METER_HEIGHT  -get duplicated later - different long names, same short names

**Comment by kinverarity1** [comment]
Yeah, we can do this in code fairly straightforwardly but it's fiddly - maybe tomorrow sometime.

**Comment by RichardScottOZ** [comment]
Thanks very much!

**Comment by kinverarity1** [comment]
One step forward:

1) I've updated `master` here (#25) to make it possible to mess with the GDF2 definition with code.
2) Here is an example of using the new `master` version of aseg_gdf2 to resolve duplicate field names - not thoroughly tested, but this simple example works: https://github.com/kinverarity1/aseg_gdf2_testdata/blob/master/duplicate_columns/read%20duplicate%20columns.ipynb

And one step back: 

The actual dataset you are trying to load now raises a different error! I'll have a look tomorrow if I have time; if you make any progress, let me know. The dfn file may be malformed in a different way.

**Comment by RichardScottOZ** [comment]
Thanks... I have not tried to read that one myself before... could editing it introduce some sort of line ending character that it doesn't like?  

I think it basically loaded ok before ... I could list fields etc., but not make a dataframe as duplicates.

**Comment by kinverarity1** [comment]
Yeah, there's something wrong with how aseg_gdf2 is reading that DFN file. `dask.read_fwf` doesn't seem to be applying the correct width of 32 chars for the 36th column (STATION1) 😭 

(problem is on the Python end, not the DFN file end)

**Comment by RichardScottOZ** [comment]
Yeah, thought it might be something like that.

**Comment by RichardScottOZ** [comment]
So if you downloaded your own, and tinkering with it I got something similar - I can try downloading it again to confirm?  Maybe have to look at that one at a low level, see if it has a character set oddity?

**Comment by kinverarity1** [comment]
Yeah, can you point me to one that you are trying to load? I am looking at the one you linked above from the GA website. I didn't think it's any character set problem, but I guess it could be!

**Comment by kinverarity1** [comment]
I have a feeling read_fwf has some funny behaviour perhaps limited to dask and dtype inference so I want to check that too. Ideally, there shouldn't be any need for dtype inference.

**Comment by RichardScottOZ** [comment]
Ok, so if you downloaded that and had problems then the same - I naively edited the .dfn to have non duplicate fields and then it crashed.

**Comment by kinverarity1** [comment]
Closing this as the remaining issue appears to relate to different behaviour between pandas and dask. Pandas works OK, dask does not.

**Comment by kinverarity1** [comment]
Sorry Richard - should have updated you on the duplicate field name problem. With the master branch this should work fine now:

![image](https://user-images.githubusercontent.com/4525931/106993553-dc2e2b00-67ca-11eb-84e5-e20f512a0868.png)

**Comment by RichardScottOZ** [comment]
Great, thanks very much Kent!

**Comment by RichardScottOZ** [comment]
Will give it a go and write something up.
