### ISSUE TITLE
errors with recent pandas versions

### ISSUE THREAD

**Issue by bamburgh** [kinverarity1/aseg_gdf2#29]
Hello,

Thanks for a very useful ASEG-GDF2 package which I use a lot! Recently there seems to be an inconsistency with later versions of pandas (and/or dark). Using dask 2.10.1 and pandas 1.4.3 I get:

/Users/markdransfield/opt/miniconda3/envs/whizz/lib/python3.10/site-packages/dask/dataframe/utils.py:366: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  _numeric_index_types = (pd.Int64Index, pd.Float64Index, pd.UInt64Index)
/Users/markdransfield/opt/miniconda3/envs/whizz/lib/python3.10/site-packages/dask/dataframe/utils.py:366: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  _numeric_index_types = (pd.Int64Index, pd.Float64Index, pd.UInt64Index)
/Users/markdransfield/opt/miniconda3/envs/whizz/lib/python3.10/site-packages/dask/dataframe/utils.py:366: FutureWarning: pandas.UInt64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  _numeric_index_types = (pd.Int64Index, pd.Float64Index, pd.UInt64Index)

Using dask 2024.2.1 and pandas 2.2.1 I get:

cannot import name 'json_normalize' from 'pandas.io.json' (/Users/markdransfield/opt/miniconda3/envs/test1/lib/python3.12/site-packages/pandas/io/json/__init__.py)

best wishes
Mark Dransfield (bamburgh)

**Comment by bamburgh** [comment]
Thanks, that works fine.

**Comment by kinverarity1** [comment]
Thanks for confirming!

**Comment by kinverarity1** [comment]
I have now published this fix to PyPI as version 0.6
